const modelOptions = [
    "Abarth 124",
    "Abarth 595",
    "Abarth 500e",
    "Abarth 1999",
    "Abarth F595",
    "Abarth 695",
    "Abarth Other",
    "Acura CSX/EL",
    "Acura MDX",
    "Acura ILX",
    "Acura RSX/Integra",
    "Acura Other",
    "Acura RDX",
    "Acura NSX",
    "Acura TLX",
    "AITO M7",
    "AITO M5",
    "AITO M9",
    "Alfa Romeo Tonale",
    "Alfa Romeo GIULIETTA",
    "Alfa Romeo Mito",
    "Alfa Romeo GTV/GT",
    "Alfa Romeo Other",
    "Alfa Romeo Giulia",
    "Alfa Romeo 8C",
    "Alfa Romeo 4C",
    "Alfa Romeo 156/159",
    "Alfa Romeo Spider",
    "Alfa Romeo Brera",
    "Alfa Romeo 166",
    "Alfa Romeo 145/146/147",
    "Alfa Romeo Stelvio",
    "Ariel Atom",
    "Ashok Leyland Falcon",
    "Ashok Leyland Oyster",
    "Ashok Leyland GAZL",
    "Ashok Leyland Partner",
    "Aston Martin DBX",
    "Aston Martin Lagonda",
    "Aston Martin DB10",
    "Aston Martin Valkyrie",
    "Aston Martin Vulcan",
    "Aston Martin One-77",
    "Aston Martin Rapide",
    "Aston Martin DB11",
    "Aston Martin Zagato",
    "Aston Martin DB7",
    "Aston Martin DB9",
    "Aston Martin DBS",
    "Aston Martin Virage",
    "Aston Martin Other",
    "Aston Martin DB12",
    "Aston Martin Vanquish",
    "Aston Martin Cygnet",
    "Aston Martin Vantage",
    "Audi S3/RS3",
    "Audi A1",
    "Audi Q3",
    "Audi Q5",
    "Audi A4",
    "Audi A7",
    "Audi SQ8",
    "Audi Q2",
    "Audi A5",
    "Audi A8",
    "Audi SQ7",
    "Audi TT",
    "Audi A6",
    "Audi Q7",
    "Audi RS Q8",
    "Audi e-tron",
    "Audi S8",
    "Audi S7/RS7",
    "Audi S5",
    "Audi S5/RS5",
    "Audi S6/RS6",
    "Audi SQ5",
    "Audi R8",
    "Audi S4/RS4",
    "Audi S3",
    "Audi RS e-tron",
    "Audi Q8",
    "Audi RSQ3",
    "Audi Other",
    "Audi A3",
    "Aurus Senat",
    "Austin-Healey Other",
    "Austin-Healey 3000",
    "Avatr 11",
    "Avatr 07",
    "Avatr Other",
    "Avatr 12",
    "BAC Mono",
    "BAIC MZ40",
    "BAIC BJ60",
    "BAIC X7",
    "BAIC A1",
    "BAIC X55",
    "BAIC A113",
    "BAIC K21",
    "BAIC BJ40 SE",
    "BAIC A523",
    "BAIC A5",
    "BAIC A115",
    "BAIC D20",
    "BAIC BJ40 C",
    "BAIC Other",
    "BAIC F40",
    "BAIC BJ40L",
    "BAIC BJ80",
    "BAIC X424",
    "BAIC MZ45",
    "BAIC X35",
    "BAW 212 T01",
    "BAW MPV",
    "BAW Pick up",
    "BAW Small Truck",
    "Bentley Azure",
    "Bentley Brooklands",
    "Bentley Continental",
    "Bentley Other",
    "Bentley Mulsanne",
    "Bentley Arnage",
    "Bentley Bentayga",
    "Bentley Flying Spur",
    "Bentley Onyx Other",
    "Bentley Onyx GTX II",
    "Bentley Onyx GTX 4x4",
    "Bentley Onyx GTX III",
    "Bentley Onyx GTX I",
    "Bestune B30",
    "Bestune B70S",
    "Bestune X80",
    "Bestune Other",
    "Bestune B50",
    "Bestune B70",
    "Bestune T77",
    "Bestune X40",
    "Bestune T55",
    "Bestune T99",
    "Bestune T33",
    "Bestune B90",
    "Bestune T77 Pro",
    "Bizzarrini Other",
    "BMW 4-Series",
    "BMW M1",
    "BMW Other",
    "BMW M8",
    "BMW iX",
    "BMW X6",
    "BMW X5",
    "BMW X1",
    "BMW M4",
    "BMW Z3",
    "BMW 8-Series",
    "BMW iX3",
    "BMW Z4",
    "BMW M5",
    "BMW M-Coupe",
    "BMW 3-Series",
    "BMW M-Roadster",
    "BMW 7-Series",
    "BMW X7",
    "BMW M2",
    "BMW Z8",
    "BMW i8",
    "BMW 2-Series",
    "BMW 6-Series",
    "BMW iX1",
    "BMW i4",
    "BMW i5",
    "BMW M3",
    "BMW iX2",
    "BMW i3",
    "BMW M6",
    "BMW X3",
    "BMW XM",
    "BMW X2",
    "BMW 1-Series",
    "BMW i7",
    "BMW 5-Series",
    "BMW Z1",
    "BMW X4",
    "BMW Alpina D4",
    "BMW Alpina XB7",
    "BMW Alpina B3",
    "BMW Alpina B7",
    "BMW Alpina B8",
    "BMW Alpina D4 S",
    "BMW Alpina D5",
    "BMW Alpina XD3",
    "BMW Alpina B5 GT",
    "BMW Alpina B5",
    "BMW Alpina D3S",
    "BMW Alpina B6",
    "BMW Alpina D5 S",
    "BMW Alpina XD4",
    "BMW Alpina B4",
    "BMW Alpina D3",
    "Borgward BX7",
    "Borgward BX5",
    "Brilliance V5",
    "Brilliance FRV",
    "Brilliance V6",
    "Brilliance V7",
    "Brilliance H530",
    "Bufori Geneva",
    "Bufori Other",
    "Bufori MK III",
    "Bugatti Veyron",
    "Bugatti Chiron",
    "Bugatti Other",
    "Bugatti Veyron 16.4",
    "Bugatti Divo",
    "Bugatti Grand Sport",
    "Bugatti Grand Sport Vitesse",
    "Bugatti Super Sport",
    "Buick Riviera",
    "Buick Other",
    "BYD F3",
    "BYD Song Plus",
    "BYD Yuan Plus",
    "BYD HAN",
    "BYD ATTO 3",
    "BYD Qin Plus",
    "BYD Qin Pro",
    "BYD Yangwang U8",
    "BYD SEALION",
    "BYD Other",
    "BYD e2",
    "BYD SEALION 7",
    "BYD Seagull",
    "BYD BYD",
    "BYD Qin",
    "BYD Leopard 8",
    "BYD Leopard",
    "BYD XIA",
    "BYD Song Pro",
    "BYD Yuan up",
    "BYD Qin L",
    "BYD Tengshi D9",
    "BYD F5",
    "BYD Seal",
    "BYD Song L",
    "BYD F7",
    "BYD F6",
    "BYD Leopard 5",
    "BYD S6",
    "BYD Dolphin",
    "BYD Tang",
    "Cadillac Escalade",
    "Cadillac XT4",
    "Cadillac XTR/Eldorado",
    "Cadillac Other",
    "Cadillac XTS",
    "Cadillac SLS",
    "Cadillac BLS",
    "Cadillac ATS",
    "Cadillac DTS/De Ville",
    "Cadillac SRX",
    "Cadillac XT6",
    "Cadillac CT5",
    "Cadillac Lyriq",
    "Cadillac Fleetwood",
    "Cadillac CTS/Catera",
    "Cadillac STS/Seville",
    "Cadillac CT6",
    "Cadillac XLR",
    "Cadillac CT4",
    "Cadillac XT5",
    "Can-am Maverick X3",
    "Can-am Maverick",
    "Caterham Seven 360",
    "Caterham Other",
    "Caterham CSR",
    "Caterham Seven 270",
    "Caterham Seven 165",
    "Caterham Seven 420",
    "Caterham 620 R",
    "CEVO C",
    "Changan CS75",
    "Changan CS75 Plus",
    "Changan Eado Plus",
    "Changan Other",
    "Changan Uni-V",
    "Changan CS35 Plus",
    "Changan Eado",
    "Changan CS35",
    "Changan E-Star",
    "Changan UNI-K",
    "Changan Alsvin",
    "Changan X5 Plus",
    "Changan Alsvin V7",
    "Changan Lumin",
    "Changan Uni-T",
    "Changan CS95",
    "Changan Starlight",
    "Changan CS85",
    "Changan Deepal G318",
    "Chery Tiggo 9",
    "Chery Other",
    "Chery A11",
    "Chery E8",
    "Chery Tiggo7 Pro",
    "Chery Arrizo 5",
    "Chery AIQAR",
    "Chery T11",
    "Chery Tiggo8 Pro",
    "Chery Tiggo 7",
    "Chery iCar",
    "Chery Arrizo 3",
    "Chery Tiggo 4",
    "Chery QQ",
    "Chery S11",
    "Chery V5",
    "Chery Arrizo 8",
    "Chery Tiggo 3",
    "Chery Tiggo 8",
    "Chery Arrizo 7",
    "Chery Tiggo 5",
    "Chery iCar 03",
    "Chery E5",
    "Chery B11",
    "Chevrolet Express",
    "Chevrolet Avalanche",
    "Chevrolet Aveo",
    "Chevrolet Optra",
    "Chevrolet Colorado",
    "Chevrolet Bel Air",
    "Chevrolet Groove",
    "Chevrolet Chevelle",
    "Chevrolet Spark",
    "Chevrolet Equinox",
    "Chevrolet Explorer",
    "Chevrolet T-Series",
    "Chevrolet Malibu",
    "Chevrolet Pickup",
    "Chevrolet Cruze",
    "Chevrolet Silverado",
    "Chevrolet Monza",
    "Chevrolet Trax",
    "Chevrolet Menlo",
    "Chevrolet Other",
    "Chevrolet Cavalier",
    "Chevrolet HHR",
    "Chevrolet Trailblazer",
    "Chevrolet Sonic",
    "Chevrolet Astro",
    "Chevrolet SSR",
    "Chevrolet Captiva",
    "Chevrolet Traverse",
    "Chevrolet Corvette",
    "Chevrolet CSV",
    "Chevrolet Nova",
    "Chevrolet Epica",
    "Chevrolet Camaro",
    "Chevrolet Impala",
    "Chevrolet Camaro Convertible",
    "Chevrolet Apache",
    "Chevrolet Lumina",
    "Chevrolet Caprice",
    "Chevrolet Suburban",
    "Chevrolet Tahoe",
    "Chevrolet Blazer",
    "Chevrolet Monte Carlo",
    "Chevrolet Uplander",
    "Chevrolet Bolt",
    "Chrysler Pacifica",
    "Chrysler Concorde",
    "Chrysler Neon",
    "Chrysler Sebring",
    "Chrysler 300",
    "Chrysler Voyager/Caravan",
    "Chrysler 300S",
    "Chrysler 300C",
    "Chrysler Prowler",
    "Chrysler PT Cruiser",
    "Chrysler Crossfire",
    "Chrysler 300M/300C",
    "Chrysler 200/200C EV",
    "Chrysler Other",
    "Chrysler 300M",
    "Citroen C4",
    "Citroen C2",
    "Citroen DS 3",
    "Citroen DS 5",
    "Citroen DS 4",
    "Citroen C-Elysee",
    "Citroen Jumper",
    "Citroen DS 21",
    "Citroen Other",
    "Citroen Berlingo",
    "Citroen SpaceTourer",
    "Citroen Traction Avant",
    "Citroen C3",
    "Citroen Saxo",
    "Citroen AX",
    "Citroen C8",
    "Citroen Xsara Picasso",
    "Citroen C5",
    "Citroen Jumpy",
    "CMC Other",
    "CMC Veryca",
    "CMC Z7",
    "Cupra Formentor",
    "Cupra Other",
    "Dacia Sandero",
    "Daewoo Lanos",
    "Daewoo Nubira",
    "Daewoo Other",
    "Daewoo Musso",
    "Daewoo Leganza",
    "Daewoo Matiz",
    "Daihatsu Terios",
    "Daihatsu Materia",
    "Daihatsu Other",
    "Daihatsu Rocky",
    "Daihatsu Sirion",
    "Daihatsu Gran Max",
    "Daihatsu Charade",
    "Daihatsu YRV",
    "Dallara Stradale",
    "Dallara Other",
    "Datsun 240Z",
    "Datsun 280Z",
    "Datsun 280ZX",
    "Datsun 810",
    "Dayun Yuehu",
    "DeLorean Other",
    "Denza Z9 GT",
    "Denza D9",
    "Devinci Marianne",
    "Devinci Eugenie",
    "Devinci Brigitte",
    "Devinci Adele",
    "DFSK Landian E5",
    "DFSK Fengguang 580",
    "DFSK Fengon 580",
    "DFSK G7",
    "DFSK Fengguang 580 Pro",
    "DFSK Glory i-Auto",
    "DFSK v21",
    "DFSK Glory 580 Pro",
    "DFSK Glory 580",
    "Dodge Magnum",
    "Dodge Charger",
    "Dodge Other",
    "Dodge Journey",
    "Dodge Caliber",
    "Dodge Pickup",
    "Dodge Avenger",
    "Dodge Challenger",
    "Dodge Van",
    "Dodge Caravan",
    "Dodge Nitro",
    "Dodge Dakota",
    "Dodge Dart",
    "Dodge Ram",
    "Dodge Stealth",
    "Dodge Neon",
    "Dodge Coronet",
    "Dodge Durango",
    "Dodge Viper",
    "DongFeng Paladin",
    "DongFeng DFSK V22",
    "DongFeng H30 Cross",
    "DongFeng S30",
    "DongFeng HUGE",
    "DongFeng Other",
    "DongFeng DFSK V21",
    "DongFeng M-Hero 917",
    "DongFeng AX7",
    "DongFeng T5",
    "DongFeng RICH 7",
    "Dorcen G60S",
    "Dorcen G60",
    "Dorcen G70",
    "Dorcen Domy X5",
    "Dorcen G70S",
    "Dorcen Domy X7",
    "Entegra Ethos",
    "Equus Bass 770",
    "Exeed Other",
    "Exeed TXL",
    "Exeed LX",
    "Exeed RX",
    "Exeed VX",
    "Faw Oley",
    "Fengon IX7",
    "Fengon 600",
    "Fengon IX5",
    "Fengon 580",
    "Fengon 500",
    "Fenyr SuperSport",
    "Ferrari 812 Superfast",
    "Ferrari 512",
    "Ferrari 430",
    "Ferrari 812 GTS",
    "Ferrari 458",
    "Ferrari 575M Maranello",
    "Ferrari Daytona",
    "Ferrari Ferrari Enzo",
    "Ferrari 246 Dino",
    "Ferrari FF",
    "Ferrari 488",
    "Ferrari SF90 Stradale",
    "Ferrari F80",
    "Ferrari Roma",
    "Ferrari 488 GTB",
    "Ferrari 599",
    "Ferrari California",
    "Ferrari 488 Spider",
    "Ferrari 458 Spider",
    "Ferrari Monza",
    "Ferrari LaFerrari",
    "Ferrari 328",
    "Ferrari Ferrari 456",
    "Ferrari La Ferrari Aperta",
    "Ferrari 599 GTB",
    "Ferrari Portofino",
    "Ferrari SF90 Spider",
    "Ferrari 812",
    "Ferrari Testarossa",
    "Ferrari F8 Tributo",
    "Ferrari 612 Scaglietti",
    "Ferrari Icona",
    "Ferrari 296 GTB",
    "Ferrari 360",
    "Ferrari F430",
    "Ferrari California T",
    "Ferrari 296 GTS",
    "Ferrari F40",
    "Ferrari 599 GTO",
    "Ferrari 412",
    "Ferrari F8 Spider",
    "Ferrari 458 Italia",
    "Ferrari 488 Pista Spider",
    "Ferrari 458 Speciale Aperta",
    "Ferrari Purosangue",
    "Ferrari GTC4 Lusso",
    "Ferrari 458 Speciale",
    "Ferrari Other",
    "Ferrari 348",
    "Ferrari 355",
    "Ferrari GTC4 Lusso T",
    "Ferrari 308",
    "Ferrari F12",
    "Ferrari Super America",
    "Ferrari Scaglietti",
    "Ferrari 488 Pista",
    "Ferrari F12 Berlinetta",
    "Ferrari 12Cilindri",
    "Ferrari Onyx F2X",
    "Ferrari Onyx 8XX",
    "Ferrari Onyx Other",
    "Ferrari Onyx SFX",
    "Fiat Sienna",
    "Fiat 600",
    "Fiat Fullback",
    "Fiat 124 Spider",
    "Fiat Tempra",
    "Fiat Linea",
    "Fiat 500e",
    "Fiat Barchetta",
    "Fiat Brava",
    "Fiat Uno",
    "Fiat Other",
    "Fiat Fiorino",
    "Fiat Marea",
    "Fiat 500L",
    "Fiat 500",
    "Fiat Ducato",
    "Fiat Bravo",
    "Fiat Punto",
    "Fiat 500X",
    "Fisker Karma",
    "Fisker Other",
    "Force Traveller",
    "Ford Bronco",
    "Ford Other",
    "Ford Explorer",
    "Ford F-Series Pickup",
    "Ford Mustang Mach-E",
    "Ford Torino",
    "Ford Ecosport",
    "Ford Mustang",
    "Ford Pickup",
    "Ford Five Hundred",
    "Ford Tourneo",
    "Ford Fusion",
    "Ford Shelby Cobra",
    "Ford Aerostar",
    "Ford Thunderbird",
    "Ford Flex",
    "Ford Mondeo",
    "Ford Ranger",
    "Ford Fiesta",
    "Ford Excursion",
    "Ford Crown Victoria",
    "Ford Escort",
    "Ford Super Duty",
    "Ford Focus",
    "Ford Edge",
    "Ford Everest",
    "Ford Maverick",
    "Ford Expedition",
    "Ford Figo",
    "Ford F-Series",
    "Ford Territory",
    "Ford Van",
    "Ford GT",
    "Ford Escape",
    "Ford Taurus",
    "Ford Transit",
    "Forthing Friday",
    "Forthing S7",
    "Forthing T5 Evo",
    "Forthing Other",
    "Forthing U-Tour",
    "Forthing T5",
    "Foton TUNLAND",
    "Foton SUP",
    "Foton Cargo Van",
    "Foton View",
    "Foton Other",
    "GAC GA6",
    "GAC GA4",
    "GAC GS8",
    "GAC Aion Y",
    "GAC Other",
    "GAC GS3",
    "GAC GS4",
    "GAC Aion Hyper",
    "GAC GA3",
    "GAC EMKOO",
    "GAC GA8",
    "GAC GS7",
    "GAC GN8",
    "GAC EMZOOM",
    "GAC M8",
    "GAC GN6",
    "GAC EMPOW",
    "GAC GS5",
    "GAC Gonow Mini Buses",
    "GAC Gonow M1/M2",
    "GAC Gonow Troy 100/500",
    "GAC Gonow Chiller Pickup",
    "Geely Emgrand X7",
    "Geely Emgrand 7",
    "Geely Emgrand X7 Sport",
    "Geely Emgrand",
    "Geely Monjaro",
    "Geely GC6",
    "Geely GX2",
    "Geely GC2",
    "Geely Preface",
    "Geely Geometry C",
    "Geely Other",
    "Geely Okvango",
    "Geely Coolray",
    "Geely GX3 Pro",
    "Geely Starray",
    "Geely Farizon",
    "Geely Emgrand 8",
    "Geely Tugella",
    "Genesis GV70",
    "Genesis Coupe",
    "Genesis G80",
    "Genesis GV80",
    "Genesis GV60",
    "Genesis G70",
    "Genesis Other",
    "Genesis G90",
    "Genty Akylone",
    "GMC Hummer",
    "GMC Yukon",
    "GMC Canyon",
    "GMC Other",
    "GMC Pickup",
    "GMC Savana",
    "GMC Terrain",
    "GMC Acadia",
    "GMC Suburban",
    "GMC Jimmy",
    "GMC Sierra",
    "GMC Envoy",
    "Grand Tiger Grandtiger Pickup",
    "Great Wall Wingle 6",
    "Great Wall Wey Gaoshan",
    "Great Wall King Kong Poer",
    "Great Wall Wingle 7",
    "Great Wall King Kong",
    "Great Wall Other",
    "Great Wall Poer",
    "Great Wall Wingle 5",
    "Gumpert Apollo",
    "Gumpert Explosion",
    "Haval H9",
    "Haval Dargo",
    "Haval Other",
    "Haval Jolion",
    "Haval H8",
    "Haval H2",
    "Haval H6",
    "Higer Other",
    "Higer Coach",
    "Higer Mini Bus",
    "Hino 300",
    "HiPhi Y",
    "HiPhi Other",
    "HiPhi Z",
    "HiPhi X",
    "Honda ZR-V",
    "Honda Fit",
    "Honda HR-V",
    "Honda S2000",
    "Honda Crosstour",
    "Honda Jazz",
    "Honda Accord",
    "Honda Crider",
    "Honda ENP2",
    "Honda City",
    "Honda Odyssey J",
    "Honda Civic",
    "Honda Pilot",
    "Honda Passport",
    "Honda Pickup",
    "Honda Prelude",
    "Honda CR-V",
    "Honda Odyssey",
    "Honda Other",
    "Honda ENP1",
    "Honda M-NV",
    "Honda ENS1",
    "Honda CR-Z",
    "Honda Van",
    "Honda Legend",
    "Honda Element",
    "Honda MR-V",
    "Hongqi HS5",
    "Hongqi HS3",
    "Hongqi E-HS9",
    "Hongqi H9",
    "Hongqi E-QM5",
    "Hongqi Ousado",
    "Hongqi HS7",
    "Hongqi H7",
    "Hongqi Other",
    "Hongqi H5",
    "Hongqi HS9",
    "Hummer H1",
    "Hummer HX",
    "Hummer H2",
    "Hummer H3T",
    "Hummer Other",
    "Hummer H3",
    "Hycan Other",
    "Hycan Z03",
    "Hyundai i10",
    "Hyundai Staria",
    "Hyundai Grandeur",
    "Hyundai Tiburon",
    "Hyundai i20",
    "Hyundai Venue",
    "Hyundai Other",
    "Hyundai Centennial",
    "Hyundai Sonata",
    "Hyundai Veracruz",
    "Hyundai Elantra",
    "Hyundai Veloster",
    "Hyundai Grand i10",
    "Hyundai Getz",
    "Hyundai Palisade",
    "Hyundai Ioniq",
    "Hyundai Matrix",
    "Hyundai Tucson",
    "Hyundai Santa Fe",
    "Hyundai i30",
    "Hyundai Casper",
    "Hyundai Entourage",
    "Hyundai H1",
    "Hyundai Terracan",
    "Hyundai Santa Cruz",
    "Hyundai Grand Santa Fe",
    "Hyundai Atos",
    "Hyundai Accent",
    "Hyundai Stargazer",
    "Hyundai Galloper",
    "Hyundai Excel",
    "Hyundai H 100",
    "Hyundai Avante",
    "Hyundai Creta",
    "Hyundai Kona",
    "Hyundai Verna",
    "Hyundai Mufasa",
    "Hyundai Mighty",
    "Hyundai Azera",
    "Hyundai Genesis",
    "Hyundai Trajet",
    "Hyundai i40",
    "Hyundai Coupe",
    "Hyundai Porter",
    "INEOS Grenadier",
    "Infiniti FX50",
    "Infiniti G-Series",
    "Infiniti EX37",
    "Infiniti Q45",
    "Infiniti Q70",
    "Infiniti G25",
    "Infiniti QX80",
    "Infiniti QX30",
    "Infiniti Q50",
    "Infiniti FX45/FX35",
    "Infiniti I35/I30",
    "Infiniti QX60",
    "Infiniti J30",
    "Infiniti Q60",
    "Infiniti JX-Series",
    "Infiniti QX55",
    "Infiniti EX35",
    "Infiniti M-Series",
    "Infiniti QX70",
    "Infiniti G35",
    "Infiniti Other",
    "Infiniti Q30",
    "Infiniti G37",
    "Infiniti Q40",
    "Infiniti FX37",
    "Infiniti QX50",
    "Infiniti QX56",
    "Infiniti QX4",
    "International MXT",
    "International CXT",
    "Isuzu Axiom",
    "Isuzu Trooper",
    "Isuzu i-Series",
    "Isuzu I Mark",
    "Isuzu Impulse",
    "Isuzu MU-X",
    "Isuzu Rodeo",
    "Isuzu Amigo",
    "Isuzu D-Max",
    "Isuzu Ascender",
    "Isuzu Stylus",
    "Isuzu Other",
    "Isuzu Oasis",
    "Iveco Daily",
    "JAC Tourist Bus",
    "JAC Other",
    "JAC J4",
    "JAC JS4",
    "JAC S3 Plus",
    "JAC S7",
    "JAC JS6",
    "JAC HK6730",
    "JAC J7",
    "JAC T8",
    "JAC M1",
    "JAC M5",
    "JAC M4",
    "JAC S3",
    "JAC E30X",
    "JAC City Bus",
    "JAC T6 Pickup",
    "JAC J6",
    "JAC J5",
    "JAECOO J7",
    "JAECOO J8",
    "Jaguar XKR",
    "Jaguar E-Type",
    "Jaguar XJS",
    "Jaguar XJ-Series",
    "Jaguar XE",
    "Jaguar S-Type",
    "Jaguar F-Type",
    "Jaguar XJ",
    "Jaguar XK8",
    "Jaguar XF",
    "Jaguar E-Pace",
    "Jaguar F-Pace",
    "Jaguar Other",
    "Jaguar XK",
    "Jaguar X-Type",
    "Jaguar I-Pace",
    "Jeep Patriot",
    "Jeep Commanche",
    "Jeep Other",
    "Jeep Wrangler 4xe",
    "Jeep Commander",
    "Jeep Wrangler Unlimited",
    "Jeep Cherokee",
    "Jeep Grand Cherokee",
    "Jeep Gladiator",
    "Jeep Wrangler",
    "Jeep Compass",
    "Jeep Renegade",
    "Jeep Grand Wagoneer",
    "Jeep Liberty",
    "Jeep Grand Cherokee L",
    "Jetour X90 Plus",
    "Jetour X70 S",
    "Jetour T2 i-DM",
    "Jetour X70",
    "Jetour Dashing",
    "Jetour X50",
    "Jetour X90",
    "Jetour Other",
    "Jetour X95",
    "Jetour X70 FL",
    "Jetour X70 Plus",
    "Jetour T2",
    "Jetour T1",
    "Jinbei DLX",
    "Jinbei H2L Highroof",
    "Jinbei Cargo Van",
    "Ji Yue 01",
    "Ji Yue Other",
    "JMC Other",
    "JMC Grand Avenue",
    "JMC NKR",
    "JMC NHR",
    "Kaiyi Other",
    "Kaiyi X7",
    "Kaiyi X3",
    "Kaiyi E5",
    "Kaiyi X3 Pro",
    "Kia Sedona",
    "Kia Carnival",
    "Kia Sephia",
    "Kia Sonet",
    "Kia K900",
    "Kia Cerato",
    "Kia Seltos",
    "Kia EV6",
    "Kia Mohave",
    "Kia Niro",
    "Kia Sportage",
    "Kia Carens",
    "Kia EV9",
    "Kia Pegas",
    "Kia Shuma",
    "Kia KX1",
    "Kia K9",
    "Kia Oprius",
    "Kia Sorento",
    "Kia EV5",
    "Kia Other",
    "Kia Cadenza",
    "Kia Optima",
    "Kia Spectra",
    "Kia Picanto",
    "Kia Morning",
    "Kia K8",
    "Kia Bongo",
    "Kia Koup",
    "Kia Telluride",
    "Kia Rio",
    "Kia Soul",
    "Kia K5",
    "Kia Quoris",
    "Kia Ray",
    "Kia K3",
    "Kia K5 HEV",
    "Kia Forte",
    "Kia Stinger",
    "King Long Small Luxury Coach",
    "King Long China Mini Van",
    "King Long Luxury Coach",
    "King Long Large Luxury Coach",
    "King Long Medium Luxury Coach",
    "King Long Other",
    "King Long Coach",
    "Koenigsegg CCGT",
    "Koenigsegg CCR",
    "Koenigsegg CC8S",
    "Koenigsegg ONE:1",
    "Koenigsegg Regera",
    "Koenigsegg CCX",
    "Koenigsegg CCXR",
    "Koenigsegg Agera",
    "Koenigsegg Jesko",
    "Koenigsegg CC Prototype",
    "KTM X-Bow",
    "Lada Other",
    "Lamborghini Revuelto",
    "Lamborghini Murcielago",
    "Lamborghini Centenario",
    "Lamborghini Countach",
    "Lamborghini Other",
    "Lamborghini Aventador",
    "Lamborghini Sián",
    "Lamborghini Diablo",
    "Lamborghini Huracan",
    "Lamborghini Gallardo",
    "Lamborghini Aventador S",
    "Lamborghini Urus",
    "Lamborghini 350 GT",
    "Lamborghini Onyx Other",
    "Lamborghini Onyx SX",
    "Lancia Phedra",
    "Lancia Stratos",
    "Lancia FX-Series",
    "Lancia Musa",
    "Lancia Delta",
    "Lancia Ypsilon",
    "Lancia Other",
    "Lancia Thesis",
    "Land Rover Discovery",
    "Land Rover Range Rover Evoque",
    "Land Rover LR2",
    "Land Rover LR3",
    "Land Rover Defender",
    "Land Rover LR4",
    "Land Rover Range Rover Velar",
    "Land Rover Discovery Sport",
    "Land Rover Other",
    "Land Rover Range Rover Sport",
    "Land Rover Freelander",
    "Land Rover Range Rover",
    "Leapmotor C10",
    "Leapmotor Other",
    "Leapmotor T03",
    "Leapmotor C16",
    "Leapmotor S01",
    "Leapmotor C11",
    "Leapmotor C01",
    "LEVC TX5",
    "Lexus UX 200",
    "Lexus RC",
    "Lexus GX 470",
    "Lexus LC 500",
    "Lexus RX-Series",
    "Lexus LM 350h",
    "Lexus ES-Series",
    "Lexus LM 300",
    "Lexus RZ",
    "Lexus LS-Series",
    "Lexus LFA",
    "Lexus SC-Series",
    "Lexus Other",
    "Lexus LX570",
    "Lexus TX",
    "Lexus CT-Series",
    "Lexus GX 460",
    "Lexus GX 550",
    "Lexus LX-Series",
    "Lexus LX600",
    "Lexus GS-Series",
    "Lexus RC F",
    "Lexus IS-Series",
    "Lexus UX-Series",
    "Lexus NX-Series",
    "Li Auto L8",
    "Li Auto Other",
    "Li Auto L6",
    "Li Auto L9",
    "Li Auto L7",
    "Li Auto Mega",
    "Lincoln Navigator",
    "Lincoln Town Car",
    "Lincoln MKT",
    "Lincoln Corsair",
    "Lincoln MKS",
    "Lincoln MKZ",
    "Lincoln MKC",
    "Lincoln Other",
    "Lincoln MKX",
    "Lincoln Aviator",
    "Lincoln LS",
    "Lincoln Continental",
    "Lincoln Nautilus",
    "Livan X3 Pro",
    "Lixiang L8",
    "Lotus Emira",
    "Lotus Eletre",
    "Lotus Evora",
    "Lotus Elan",
    "Lotus Emeya",
    "Lotus Elise",
    "Lotus Exige",
    "Lotus Esprit",
    "Lotus Other",
    "Lucid Air",
    "Luxgen 7 SUV",
    "Luxgen S5",
    "Luxgen 7 MPV",
    "Luxgen U6",
    "Luxgen Other",
    "Luxgen U7 Turbo",
    "Lynk & Co Z10",
    "Lynk & Co 05",
    "Lynk & Co 01",
    "Lynk & Co Z20",
    "Lynk & Co 09",
    "Lynk & Co Others",
    "Mahindra XUV 500",
    "Mahindra Scorpio Pickup",
    "Maserati GranCabrio",
    "Maserati Ghibli",
    "Maserati Coupe",
    "Maserati Levante",
    "Maserati MC20",
    "Maserati Spyder",
    "Maserati 4200",
    "Maserati Grecale",
    "Maserati MC12",
    "Maserati Quattroporte",
    "Maserati GranTurismo",
    "Maserati Other",
    "Maserati GranSport",
    "Maxus D90",
    "Maxus Other",
    "Maxus V80",
    "Maxus G10",
    "Maxus T60",
    "Maxus G20",
    "Maybach 57",
    "Maybach Other",
    "Maybach 62",
    "Mazda 626",
    "Mazda CX-7",
    "Mazda RX-7",
    "Mazda 2",
    "Mazda Pickup",
    "Mazda BT-50",
    "Mazda MX-6",
    "Mazda Tribute",
    "Mazda 323",
    "Mazda CX-90",
    "Mazda Other",
    "Mazda MX-5",
    "Mazda 929",
    "Mazda B-Series",
    "Mazda 6",
    "Mazda CX-5",
    "Mazda RX-8",
    "Mazda Navajo",
    "Mazda CX-3",
    "Mazda Protege",
    "Mazda MPV",
    "Mazda CX-60",
    "Mazda CX-30",
    "Mazda 3 Hatchback",
    "Mazda 3",
    "Mazda CX-9",
    "McLaren Other",
    "McLaren P1",
    "McLaren 675LT",
    "McLaren GT",
    "McLaren 650S",
    "McLaren Elva",
    "McLaren Speedtail",
    "McLaren 600LT",
    "McLaren Artura",
    "McLaren MP4-12C",
    "McLaren 570S",
    "McLaren 540C",
    "McLaren F1",
    "McLaren 765LT",
    "McLaren 750S",
    "McLaren 720S",
    "McLaren 570GT",
    "McLaren SLR",
    "McLaren Senna",
    "Mercedes-Benz GLC 63",
    "Mercedes-Benz R-Class",
    "Mercedes-Benz X Class",
    "Mercedes-Benz E-Class",
    "Mercedes-Benz SEC-Class",
    "Mercedes-Benz B-Class",
    "Mercedes-Benz Sprinter",
    "Mercedes-Benz SLC",
    "Mercedes-Benz C 43 AMG",
    "Mercedes-Benz Vito Panel Vans",
    "Mercedes-Benz 190",
    "Mercedes-Benz GLE-Class",
    "Mercedes-Benz GLC",
    "Mercedes-Benz AMG",
    "Mercedes-Benz A-Class",
    "Mercedes-Benz CLC",
    "Mercedes-Benz 400/420",
    "Mercedes-Benz Vito Tourer",
    "Mercedes-Benz GL-Class",
    "Mercedes-Benz CLE-Class",
    "Mercedes-Benz SLS",
    "Mercedes-Benz 300/350/380",
    "Mercedes-Benz Other",
    "Mercedes-Benz 220 SE",
    "Mercedes-Benz V-Class",
    "Mercedes-Benz Viano",
    "Mercedes-Benz EQA",
    "Mercedes-Benz SLK-Class",
    "Mercedes-Benz SLR",
    "Mercedes-Benz GLK-Class",
    "Mercedes-Benz C-Class",
    "Mercedes-Benz G-Class",
    "Mercedes-Benz C 63 AMG",
    "Mercedes-Benz G-Class Brabus",
    "Mercedes-Benz CLS-Class",
    "Mercedes-Benz EQC",
    "Mercedes-Benz Vito",
    "Mercedes-Benz EQE",
    "Mercedes-Benz SEL-Class",
    "Mercedes-Benz CL-Class",
    "Mercedes-Benz CLA",
    "Mercedes-Benz CLK-Class",
    "Mercedes-Benz 500/560",
    "Mercedes-Benz S-Class",
    "Mercedes-Benz M-Class",
    "Mercedes-Benz GLS-Class",
    "Mercedes-Benz GLB",
    "Mercedes-Benz EQV",
    "Mercedes-Benz S580e",
    "Mercedes-Benz GLE Coupe",
    "Mercedes-Benz GLA",
    "Mercedes-Benz SL-Class",
    "Mercedes-Benz 240/260/280",
    "Mercedes-Benz EQG",
    "Mercedes-Benz GLC Coupe",
    "Mercedes-Benz EQB",
    "Mercedes-Benz EQS",
    "Mercedes-Maybach GLS-Class",
    "Mercedes-Maybach S-Class",
    "Mercedes-Maybach Other",
    "Mercedes Onyx G7X",
    "Mercedes Onyx G7",
    "Mercedes Onyx G8",
    "Mercedes Onyx Other",
    "Mercedes Onyx G6",
    "Mercedes Onyx G9X",
    "Mercury Milan",
    "Mercury Montego",
    "Mercury Grand Marquis",
    "Mercury Mariner",
    "Mercury Mountaineer",
    "Mercury Other",
    "MG MG5",
    "MG MGB",
    "MG 360",
    "MG MG350",
    "MG HS",
    "MG MG750",
    "MG 6",
    "MG RX8",
    "MG B",
    "MG RX5",
    "MG Other",
    "MG A",
    "MG One",
    "MG Whale",
    "MG T60",
    "MG MG 7",
    "MG MG3",
    "MG GS",
    "MG MG550",
    "MG RX9",
    "MG ZST",
    "MG MG6",
    "MG ZS",
    "MG GT",
    "Milan Red",
    "MINI Roadster",
    "MINI Cooper Clubman",
    "MINI Cooper",
    "MINI Aceman",
    "MINI Countryman",
    "MINI Coupe",
    "MINI Mayfair",
    "MINI Clubman",
    "MINI Paceman",
    "MINI Other",
    "Mitsubishi Colt",
    "Mitsubishi Van",
    "Mitsubishi Mirage",
    "Mitsubishi Xpander",
    "Mitsubishi Pajero",
    "Mitsubishi Outlander",
    "Mitsubishi Montero Sport",
    "Mitsubishi Xpander Cross",
    "Mitsubishi Nativa",
    "Mitsubishi Galant",
    "Mitsubishi ASX",
    "Mitsubishi Evolution",
    "Mitsubishi Pajero Sport",
    "Mitsubishi Other",
    "Mitsubishi Fortis",
    "Mitsubishi Triton",
    "Mitsubishi L200",
    "Mitsubishi Canter",
    "Mitsubishi Diamonte",
    "Mitsubishi Lancer",
    "Mitsubishi Montero",
    "Mitsubishi Attrage",
    "Mitsubishi Lancer EX",
    "Mitsubishi EclipseCross",
    "Mitsubishi Grandis",
    "Mitsubishi 3000GT",
    "Mitsubishi Pickup",
    "Mitsubishi Eclipse",
    "Mitsubishi Magna",
    "Morgan Aero Supersport",
    "Morgan Aero 8",
    "Morgan Plus 6",
    "Morgan 4 Seater",
    "Morgan Plus 4",
    "Morgan Plus 8",
    "Morgan Roadster",
    "Morgan 4/4",
    "Morgan Aero Coupe",
    "Morgan 3 Wheeler",
    "Morris Minor",
    "Neta Other",
    "Neta Aya",
    "Nio ES8",
    "Nio ES6",
    "Nio ES7",
    "Nissan Skyline",
    "Nissan Terrano",
    "Nissan Patrol Safari",
    "Nissan Titan",
    "Nissan Maxima",
    "Nissan GT-R",
    "Nissan Pathfinder",
    "Nissan Tiida",
    "Nissan Rogue",
    "Nissan 370z",
    "Nissan Silvia",
    "Nissan Navara",
    "Nissan S130",
    "Nissan Ariya",
    "Nissan Urvan",
    "Nissan Micra",
    "Nissan X-Trail",
    "Nissan 280ZX",
    "Nissan Altima",
    "Nissan Sunny",
    "Nissan Van",
    "Nissan Armada",
    "Nissan Other",
    "Nissan 400Z",
    "Nissan Patrol",
    "Nissan Quest",
    "Nissan Sylphy",
    "Nissan Leaf",
    "Nissan Xterra",
    "Nissan Magnite",
    "Nissan Kicks",
    "Nissan Z",
    "Nissan Primera",
    "Nissan Juke",
    "Nissan 350Z",
    "Nissan Versa",
    "Nissan Patrol Pickup",
    "Nissan Qashqai",
    "Nissan Pickup",
    "Nissan Gloria",
    "Nissan Murano",
    "Nissan 300ZX",
    "Nissan Sentra",
    "Nissan Teana",
    "Noble M600",
    "Oldsmobile Delta 88",
    "OMODA OMODA C5",
    "Opel Vita",
    "Opel Vivaro",
    "Opel Zafira Life",
    "Opel Crossland X",
    "Opel Zafira",
    "Opel Vectra",
    "Opel Mokka",
    "Opel Antara",
    "Opel Cascada",
    "Opel Meriva",
    "Opel Insignia",
    "Opel Grandland X",
    "Opel Omega",
    "Opel Kadett",
    "Opel Astra",
    "Opel Signum",
    "Opel Other",
    "Opel Corsa",
    "Other Make Other Minivan",
    "Other Make Other Pickup",
    "Other Make Heavy Vehicles",
    "Other Make Other Car",
    "Other Make Other 4x4",
    "Other Make F1",
    "Other Make Other Utility",
    "Oullim Other",
    "Oullim SPIRRA",
    "Pagani Zonda",
    "Pagani Huayra",
    "PAL-V Pioneer Limited Edition",
    "PAL-V Sport Edition",
    "Peugeot 407",
    "Peugeot RCZ",
    "Peugeot iOn",
    "Peugeot Boxer",
    "Peugeot e-208",
    "Peugeot 208",
    "Peugeot RC7",
    "Peugeot Expert",
    "Peugeot 307",
    "Peugeot 301",
    "Peugeot Traveller",
    "Peugeot 3008",
    "Peugeot e-2008",
    "Peugeot 607",
    "Peugeot Partner",
    "Peugeot 508",
    "Peugeot 5008",
    "Peugeot 504/5",
    "Peugeot 2008",
    "Peugeot Landtrek",
    "Peugeot 207",
    "Peugeot 206",
    "Peugeot Other",
    "Peugeot Rifter",
    "Peugeot 408",
    "Peugeot 308",
    "PGO Speedster",
    "Plymouth Other",
    "Plymouth GTX",
    "Polestar Other",
    "Polestar 6",
    "Polestar 3",
    "Polestar 1",
    "Polestar 4",
    "Polestar 2",
    "Pontiac Firebird",
    "Pontiac Catalina",
    "Pontiac Trans Am",
    "Pontiac GTO",
    "Pontiac Other",
    "Porsche 918 Spyder",
    "Porsche Carrera / 911",
    "Porsche Taycan",
    "Porsche 968",
    "Porsche Panamera",
    "Porsche Boxster",
    "Porsche 718 Spyder",
    "Porsche Cayenne",
    "Porsche 928",
    "Porsche 944",
    "Porsche Other",
    "Porsche Cayman",
    "Porsche Macan",
    "Proton Other",
    "Proton Savvy",
    "Proton Wira",
    "Proton Waja",
    "Proton Saga",
    "Qiantu K50",
    "Rabdan One",
    "RAM Other",
    "RAM 1500 TRX",
    "RAM Warlock",
    "RAM 2500",
    "RAM 1500",
    "Renault Duster",
    "Renault Talisman",
    "Renault Captur",
    "Renault Sandero",
    "Renault Scenic",
    "Renault Laguna",
    "Renault Koleos",
    "Renault Master",
    "Renault Zoe",
    "Renault Dokker",
    "Renault Twizy",
    "Renault Espace",
    "Renault Logan",
    "Renault Trafic",
    "Renault Fluence",
    "Renault Express Van",
    "Renault Safrane",
    "Renault Twingo",
    "Renault Arkana",
    "Renault Other",
    "Renault Megane",
    "Renault Samsung",
    "Renault Clio",
    "Renault Symbol",
    "Riddara RD6",
    "Rivian R1T",
    "Rivian R1S",
    "Roewe RX5",
    "Roewe i5",
    "Roewe RX8",
    "Rolls-Royce Silver Shadow",
    "Rolls-Royce Phantom",
    "Rolls-Royce Silver Spur",
    "Rolls-Royce Ghost",
    "Rolls-Royce Cullinan",
    "Rolls-Royce Other",
    "Rolls-Royce Wraith",
    "Rolls-Royce Spectre",
    "Rolls-Royce Silver Seraph",
    "Rolls-Royce Dawn",
    "Rolls-Royce Onyx Other",
    "Rolls-Royce Onyx Cullinan",
    "Rolls-Royce Onyx Dawn",
    "Rolls-Royce Onyx Wraith",
    "Rover Other",
    "Rover 75",
    "Rox 01",
    "Rox Other",
    "Saab 9-7x",
    "Saab 9000",
    "Saab 9-3",
    "Saab 9-5",
    "Saab Other",
    "Saab 9-2x",
    "Saab 900",
    "Seat Cordoba",
    "Seat Alhambra",
    "Seat Other",
    "Seat Altea",
    "Seat Ibiza",
    "Seat Toledo",
    "Seat Leon",
    "Seat Exeo",
    "Seres 5",
    "Seres 3",
    "Seres Other",
    "Shenlong/Sunlong SLK 6120",
    "Shenlong/Sunlong SLK 6112",
    "Skoda Roomster",
    "Skoda Karoq",
    "Skoda Kamiq",
    "Skoda Superb",
    "Skoda Scala",
    "Skoda Kodiaq",
    "Skoda Yeti",
    "Skoda Kushaq",
    "Skoda Octavia",
    "Skoda Fabia",
    "Skoda Other",
    "Skoda Rapid",
    "Skywell ET5",
    "Smart #1",
    "Smart #3",
    "Smart Other",
    "Smart Forfour",
    "Smart Fortwo",
    "Soueast DX7",
    "Soueast DX8",
    "Soueast DX3",
    "Soueast DX5",
    "Soueast S06",
    "Soueast S09",
    "Soueast S07",
    "Speranza Other",
    "Spyker C8 Preliator",
    "SsangYong Other",
    "SsangYong Rexton",
    "SsangYong Korando",
    "SsangYong Tivoli",
    "SsangYong Kyron",
    "SsangYong Rodius",
    "SsangYong Musso",
    "Stelato S9",
    "Studebaker President",
    "Subaru XV",
    "Subaru Outback",
    "Subaru Legacy",
    "Subaru Forester",
    "Subaru Crosstrek",
    "Subaru Impreza",
    "Subaru Other",
    "Subaru WRX",
    "Subaru Tribeca",
    "Subaru BRZ",
    "Suzuki Ignis",
    "Suzuki Other",
    "Suzuki Ertiga",
    "Suzuki Fronx",
    "Suzuki Celerio",
    "Suzuki Alto",
    "Suzuki Carry",
    "Suzuki Baleno",
    "Suzuki XL7",
    "Suzuki SX4",
    "Suzuki Kizashi",
    "Suzuki Dzire",
    "Suzuki S-PRESSO",
    "Suzuki Liana",
    "Suzuki Ciaz",
    "Suzuki Jimny",
    "Suzuki Eeco",
    "Suzuki Vitara",
    "Suzuki APV Van",
    "Suzuki Swift",
    "Suzuki Grand Vitara",
    "TANK 500",
    "TANK 300",
    "TATA Van",
    "TATA Zenon",
    "TATA Indigo",
    "TATA Other",
    "TATA Delivery Truck",
    "TATA Pickup",
    "Tesla Cybertruck",
    "Tesla Model 3",
    "Tesla Model X",
    "Tesla Tesla Roadster",
    "Tesla Model S",
    "Tesla Model Y",
    "Tesla Other",
    "Togg T10X",
    "Togg T10F",
    "Tova J14",
    "Toyota Supra",
    "Toyota GR86",
    "Toyota Celica",
    "Toyota 4Runner",
    "Toyota Vitz",
    "Toyota Veloz",
    "Toyota Tundra",
    "Toyota Sienna",
    "Toyota Sequoia",
    "Toyota Yaris",
    "Toyota Venza",
    "Toyota Scion",
    "Toyota Other",
    "Toyota Levin",
    "Toyota Fortuner",
    "Toyota Prius",
    "Toyota Zelas",
    "Toyota Land Cruiser 70",
    "Toyota iA",
    "Toyota Mirai",
    "Toyota Tacoma",
    "Toyota Avalon",
    "Toyota bZ3",
    "Toyota Tercel",
    "Toyota Land Cruiser 79 series",
    "Toyota Previa",
    "Toyota Innova",
    "Toyota Hilux",
    "Toyota Wigo",
    "Toyota Echo",
    "Toyota Corona",
    "Toyota 86",
    "Toyota Raize",
    "Toyota Frontlander",
    "Toyota Rumion",
    "Toyota Land Cruiser",
    "Toyota Highlander",
    "Toyota Camry",
    "Toyota Crown",
    "Toyota Urban Cruiser",
    "Toyota Land Cruiser 76 series",
    "Toyota C-HR",
    "Toyota FJ Cruiser",
    "Toyota Pickup",
    "Toyota XA",
    "Toyota Aurion",
    "Toyota Land Cruiser 71",
    "Toyota Corolla",
    "Toyota BZ4X",
    "Toyota MR2",
    "Toyota Rush",
    "Toyota Alphard",
    "Toyota Prado",
    "Toyota Corolla Cross",
    "Toyota Avensis",
    "Toyota Coaster",
    "Toyota Wish",
    "Toyota MR2 Spyder",
    "Toyota IQ",
    "Toyota Hiace",
    "Toyota Avanza",
    "Toyota Cressida",
    "Toyota Granvia",
    "Toyota Rav 4",
    "Triumph TR3",
    "Triumph Other",
    "Triumph TR4A",
    "UAZ New Patriot",
    "UAZ Commercial",
    "UAZ Hunter",
    "UAZ Cargo",
    "UAZ New Pickup",
    "VGV U70 PRO",
    "VGV Other",
    "VGV U70 PLUS",
    "VGV U75 PLUS",
    "VGV VX7",
    "VGV Bolden",
    "Victory Other",
    "Victory V2",
    "Victory V1",
    "Volkswagen Arteon",
    "Volkswagen Eos",
    "Volkswagen Atlas",
    "Volkswagen Sharan",
    "Volkswagen Eurovan",
    "Volkswagen Bora",
    "Volkswagen Polo",
    "Volkswagen Crafter",
    "Volkswagen T-Roc",
    "Volkswagen Touareg",
    "Volkswagen ID.6",
    "Volkswagen Teramont",
    "Volkswagen ID.7",
    "Volkswagen Amarok",
    "Volkswagen Vento",
    "Volkswagen ID.4",
    "Volkswagen Other",
    "Volkswagen Passat",
    "Volkswagen Transporter",
    "Volkswagen Viloran",
    "Volkswagen Beetle",
    "Volkswagen Multivan",
    "Volkswagen CC",
    "Volkswagen Phaeton",
    "Volkswagen TAYRON",
    "Volkswagen Taos",
    "Volkswagen E-Lavida",
    "Volkswagen Routan",
    "Volkswagen Golf",
    "Volkswagen Scirocco",
    "Volkswagen ID.3",
    "Volkswagen Jetta",
    "Volkswagen Tiguan",
    "Volkswagen Touran",
    "Volkswagen Caddy",
    "Volvo EX30",
    "Volvo XC40",
    "Volvo V-Class",
    "Volvo S80",
    "Volvo C-Class",
    "Volvo S40",
    "Volvo XC90",
    "Volvo XC60",
    "Volvo V90",
    "Volvo S70",
    "Volvo XC40 Recharge",
    "Volvo S90",
    "Volvo C40",
    "Volvo XC70",
    "Volvo Other",
    "Volvo S60",
    "Voyah Free",
    "Voyah Dreamer",
    "Westfield Sportscars Sport 250",
    "Westfield Sportscars Special Edition",
    "Westfield Sportscars Track",
    "Westfield Sportscars Classic",
    "Wiesmann Other",
    "Wiesmann MF5",
    "Wiesmann MF4",
    "Wiesmann MF3",
    "W Motors Fenyr Hypersport",
    "W Motors Lykan Hypersport",
    "Wuling Bingo",
    "Wuling Air EV",
    "Wuling Other",
    "XEV Other",
    "XEV Yoyo",
    "Xiaomi Other",
    "Xiaomi SU7",
    "XPeng Other",
    "XPeng G9",
    "XPeng P7",
    "YangWang Other",
    "YangWang U8",
    "Zeekr Other",
    "Zeekr X",
    "Zeekr 001 FR",
    "Zeekr 009",
    "Zeekr 007",
    "Zeekr 9",
    "Zeekr 001",
    "Zenvo Aurora",
    "Zenvo TSR-S",
    "Zhongxing Terralord",
    "ZNA Yumsun",
    "ZNA Rich",
    "ZNA Oting",
    "Zotye E200",
    "Zotye T600 Sport",
    "Zotye T300",
    "Zotye T600",
    "Zotye T700",
    "Zotye Z100",
    "ZXAUTO Other",
    "ZXAUTO Grandlion",
    "ZXAUTO Terralord"
];

export default modelOptions;

[
    {
        "model": "Abarth 124",
        "trims": [
            "Spider",
            "Other"
        ]
    },
    {
        "model": "Abarth 595",
        "trims": [
            "C Competizione",
            "Competizione",
            "Scorpioneoro",
            "Other"
        ]
    },
    {
        "model": "Abarth 500e",
        "trims": [
            "Base",
            "Other",
            "Scorpionissima",
            "Tourismo"
        ]
    },
    {
        "model": "Abarth 1999",
        "trims": [
            "Scorpioneoro"
        ]
    },
    {
        "model": "Abarth F595",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "Abarth 695",
        "trims": [
            "70th Anniversario",
            "Rivale",
            "Turismo",
            "Other"
        ]
    },
    {
        "model": "Abarth Other",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "Acura CSX/EL",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "Acura MDX",
        "trims": [
            "Advance AND Entertainment Package",
            "Advance Package",
            "Advance Plus",
            "Sport AND Entertainment Package",
            "Sport Package",
            "Standard",
            "Technology AND Entertainment Package",
            "Technology Package",
            "Technology Plus Package",
            "Other"
        ]
    },
    {
        "model": "Acura ILX",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "Acura RSX/Integra",
        "trims": [
            "Standard",
            "Type-s",
            "Other"
        ]
    },
    {
        "model": "Acura Other",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "Acura RDX",
        "trims": [
            "Advance",
            "Standard",
            "Technology Package",
            "Technology Plus Package",
            "Other"
        ]
    },
    {
        "model": "Acura NSX",
        "trims": [
            "Sport",
            "Other"
        ]
    },
    {
        "model": "Acura TLX",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "AITO M7",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "AITO M5",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "AITO M9",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "Alfa Romeo Tonale",
        "trims": [
            "Veloce",
            "other"
        ]
    },
    {
        "model": "Alfa Romeo GIULIETTA",
        "trims": [
            "Distinctive",
            "Mid",
            "Premium",
            "Quadrifoglio",
            "Special Super Series",
            "Standard",
            "Super",
            "Super Comfort",
            "Super Lusso",
            "Super Visibility",
            "Turbo Basic",
            "Turbo Full",
            "Veloce",
            "Other"
        ]
    },
    {
        "model": "Alfa Romeo Mito",
        "trims": [
            "Distinctive",
            "Progression",
            "Quadrifoglio",
            "Standard",
            "TOP",
            "Other"
        ]
    },
    {
        "model": "Alfa Romeo GTV/GT",
        "trims": [
            "Standard",
            "Other"
        ]
    },
    {
        "model": "Alfa Romeo Other",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "Alfa Romeo Giulia",
        "trims": [
            "Quadrifoglio",
            "Quadrifoglio Carbon",
            "Standard",
            "Super",
            "Super AFS",
            "Super Luxury Pack",
            "Super Sport Pack",
            "Veloce",
            "Other"
        ]
    },
    {
        "model": "Alfa Romeo 8C",
        "trims": [
            "Competizione",
            "Spider",
            "Other"
        ]
    },
    {
        "model": "Alfa Romeo 4C",
        "trims": [
            "Launch Edition",
            "Spider",
            "Sport",
            "Other"
        ]
    },
    {
        "model": "Alfa Romeo 156/159",
        "trims": [
            "Standard",
            "TOP",
            "Other"
        ]
    },
    {
        "model": "Alfa Romeo Spider",
        "trims": [
            "Sport",
            "Other"
        ]
    },
    {
        "model": "Alfa Romeo Brera",
        "trims": [
            "Standard",
            "Top",
            "Other"
        ]
    },
    {
        "model": "Alfa Romeo 166",
        "trims": [
            "Standard",
            "TOP",
            "Other"
        ]
    },
    {
        "model": "Alfa Romeo 145/146/147",
        "trims": [
            "Standard",
            "TOP",
            "other"
        ]
    },
    {
        "model": "Alfa Romeo Stelvio",
        "trims": [
            "First Edition",
            "Light Edition",
            "Premium",
            "Quadrifoglio",
            "S",
            "Super",
            "Veloce",
            "Other"
        ]
    },
    {
        "model": "Ariel Atom",
        "trims": [
            "4",
            "Other"
        ]
    },
    {
        "model": "Ashok Leyland Falcon",
        "trims": [
            "25 Seats",
            "63 Seats",
            "71 Seats"
        ]
    },
    {
        "model": "Ashok Leyland Oyster",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "Ashok Leyland GAZL",
        "trims": [
            "25 Seats",
            "Other"
        ]
    },
    {
        "model": "Ashok Leyland Partner",
        "trims": [
            "4 TYRE"
        ]
    },
    {
        "model": "Aston Martin DBX",
        "trims": [
            "550",
            "707",
            "Other"
        ]
    },
    {
        "model": "Aston Martin Lagonda",
        "trims": [
            "Standard",
            "Taraf",
            "Other"
        ]
    },
    {
        "model": "Aston Martin DB10",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "Aston Martin Valkyrie",
        "trims": [
            "AMR Pro",
            "Coupe",
            "Spider"
        ]
    },
    {
        "model": "Aston Martin Vulcan",
        "trims": [
            "Performance",
            "Other"
        ]
    },
    {
        "model": "Aston Martin One-77",
        "trims": [
            "Limited Edition",
            "Other"
        ]
    },
    {
        "model": "Aston Martin Rapide",
        "trims": [
            "AMR",
            "Luxury",
            "S",
            "S Shadow Edition",
            "Standard",
            "Other"
        ]
    },
    {
        "model": "Aston Martin DB11",
        "trims": [
            "AMR",
            "Launch edition",
            "Standard",
            "V12 Coupe",
            "V8 Coupe",
            "V8 Volante",
            "Other"
        ]
    },
    {
        "model": "Aston Martin Zagato",
        "trims": [
            "Icon",
            "Special",
            "Other"
        ]
    },
    {
        "model": "Aston Martin DB7",
        "trims": [
            "GT",
            "Luxury Edition",
            "Sport Edition",
            "Standard",
            "Vantage",
            "Volante",
            "Other"
        ]
    },
    {
        "model": "Aston Martin DB9",
        "trims": [
            "Carbon Black",
            "GT",
            "GT Carbon Black",
            "Luxury Edition",
            "Other",
            "Sport Edition",
            "Standard",
            "Volante",
            "Volante Carbon Black"
        ]
    },
    {
        "model": "Aston Martin DBS",
        "trims": [
            "Carbon Edition",
            "Standard",
            "V12",
            "V12 770 Ultimate",
            "V12 Superleggera Volante",
            "Volante",
            "Volante Carbon Black",
            "Volante Carbon Edition",
            "Other"
        ]
    },
    {
        "model": "Aston Martin Virage",
        "trims": [
            "Standard",
            "Volante",
            "Other"
        ]
    },
    {
        "model": "Aston Martin Other",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "Aston Martin DB12",
        "trims": [
            "Coupe",
            "Goldfinger",
            "Volante",
            "Other"
        ]
    },
    {
        "model": "Aston Martin Vanquish",
        "trims": [
            "Carbon Black",
            "S",
            "S Super GT",
            "Sport",
            "Standard",
            "Ultimate GT",
            "Volante",
            "Volante Carbon Black",
            "Other"
        ]
    },
    {
        "model": "Aston Martin Cygnet",
        "trims": [
            "City",
            "Other"
        ]
    },
    {
        "model": "Aston Martin Vantage",
        "trims": [
            "F1 Edition",
            "GT12",
            "GT3",
            "GT8",
            "N430",
            "Roadster",
            "S",
            "S Roadster",
            "Sport",
            "Standard",
            "Standard (V8)",
            "V12",
            "Other"
        ]
    },
    {
        "model": "Audi S3/RS3",
        "trims": [
            "2.5 TFSI",
            "RS",
            "Standard",
            "TFSI Quattro",
            "TFSI S Tronic",
            "Other"
        ]
    },
    {
        "model": "Audi A1",
        "trims": [
            "Ambition",
            "Attraction",
            "S",
            "S-line",
            "Standard",
            "Other"
        ]
    },
    {
        "model": "Audi Q3",
        "trims": [
            "30 TFSI",
            "30 TFSI Design",
            "35 TFSI",
            "35 TFSI Advanced",
            "35 TFSI Design Quattro",
            "35 TFSI Quattro",
            "35 TFSI S-Line",
            "40 TFSI",
            "40 TFSI Advanced",
            "40 TFSI Design Quattro",
            "40 TFSI S-Line",
            "45 TFSI Quattro",
            "RS",
            "S-line",
            "Standard",
            "Other"
        ]
    },
    {
        "model": "Audi Q5",
        "trims": [
            "40 TFSI Quattro",
            "40 TFSI Quattro Design",
            "40 TFSI Quattro Sport",
            "45 TFSI",
            "45 TFSI S-Line Quattro",
            "45TFSI Quattro",
            "S-line",
            "Sport 2.0 45 TFSI Quattro S Tronic",
            "SQ5 Quattro",
            "Standard",
            "TFSI",
            "Other"
        ]
    },
    {
        "model": "Audi A4",
        "trims": [
            "40 TFSI Quattro Design",
            "Standard",
            "S-line",
            "RS 4 Avant",
            "50 TFSI Quattro",
            "45 TFSI Quattro Sport",
            "40 TFSI Sport",
            "40 TFSI S-line",
            "2.0 TFSI Quattro S",
            "40 TFSI Design",
            "40 TFSI Basic",
            "40 TFSI Advanced",
            "35 TFSI S-line",
            "35 TFSI Advanced",
            "30 TFSI Sport",
            "30 TFSI Design",
            "30 TFSI Basic",
            "Other"
        ]
    },
    {
        "model": "Audi A7",
        "trims": [
            "3.0 TFSI Quattro S tronic",
            "S-line",
            "Special Edition",
            "Sportback 55 TFSI Quattro",
            "Standard",
            "Other"
        ]
    },
    {
        "model": "Audi SQ8",
        "trims": [
            "Plus",
            "Premium",
            "Prestige",
            "TFSI Quattro",
            "Other"
        ]
    },
    {
        "model": "Audi Q2",
        "trims": [
            "Basic 30",
            "Design 35",
            "Sport 30",
            "Sport 35",
            "Other"
        ]
    },
    {
        "model": "Audi A5",
        "trims": [
            "40 TFSI",
            "40 TFSI Advanced",
            "40 TFSI Design",
            "40 TFSI S-Line",
            "40 TFSI Sport",
            "45 TFSI Design Quattro",
            "45 TFSI Sport Quattro",
            "Cabriolet",
            "RS 5",
            "RS 5 S-line",
            "S-line",
            "Sportback 2.0 TFSI",
            "Standard",
            "TFSI",
            "Other"
        ]
    },
    {
        "model": "Audi A8",
        "trims": [
            "50 TFSI Quattro",
            "50 TFSI Quattro Sport",
            "55 TFSI Quattro",
            "60 TFSI Quattro",
            "60 TFSI Quattro Sport",
            "L",
            "L S-line",
            "L Special Edition",
            "L W12",
            "Luxury",
            "S-line",
            "Standard",
            "W12 FSI Quattro",
            "Other"
        ]
    },
    {
        "model": "Audi SQ7",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "Audi TT",
        "trims": [
            "45 TFSI",
            "45 TFSI Quattro",
            "Premium",
            "Quattro",
            "Roadster",
            "Roadster Quattro",
            "RS",
            "RS Plus",
            "S",
            "S-Line",
            "S Special Edition",
            "Sport Package",
            "Standard",
            "TTS",
            "Other"
        ]
    },
    {
        "model": "Audi A6",
        "trims": [
            "55 TFSI Design Quattro",
            "TFSI V6",
            "Standard",
            "S-line",
            "RS 6 S-line",
            "RS 6",
            "FSI Quattro",
            "55 TFSI Quattro",
            "35 TFSI",
            "45 TFSI Special Edition",
            "45 TFSI Quattro",
            "45 TFSI Desing Quattro",
            "45 TFSI",
            "40 TFSI Quattro",
            "40 TFSI",
            "35 TFSI Quattro",
            "Other"
        ]
    },
    {
        "model": "Audi Q7",
        "trims": [
            "3.0 TFSI Quattro Tiptronic",
            "40 TFSI CS Quattro",
            "40 TFSI Design Quattro",
            "40 TFSI Sport Quattro",
            "45 TFSI CS Quattro",
            "45 TFSI Design Quattro",
            "45 TFSI Quattro",
            "45 TFSI S-Line Quattro",
            "45 TFSI Sport Quattro",
            "55 TFSI quattro",
            "L",
            "S-line",
            "Standard",
            "Other"
        ]
    },
    {
        "model": "Audi RS Q8",
        "trims": [
            "TFSI V8 Quattro",
            "Other"
        ]
    },
    {
        "model": "Audi e-tron",
        "trims": [
            "50 Quattro",
            "GT",
            "Premium",
            "Premium Plus",
            "Prestige",
            "Q2L",
            "Other"
        ]
    },
    {
        "model": "Audi S8",
        "trims": [
            "Plus",
            "Pro Line Plus",
            "S-Line",
            "Standard",
            "TFSI Quattro",
            "Other"
        ]
    },
    {
        "model": "Audi S7/RS7",
        "trims": [
            "4.0 TFSI Quattro Tiptronic",
            "Prestige",
            "RS",
            "Standard",
            "Other"
        ]
    },
    {
        "model": "Audi S5",
        "trims": [
            "TFSI Quattro"
        ]
    },
    {
        "model": "Audi S5/RS5",
        "trims": [
            "RS",
            "Sportback Quattro",
            "Standard",
            "TFSI Quattro",
            "Other"
        ]
    },
    {
        "model": "Audi S6/RS6",
        "trims": [
            "Avant TFSI Quattro",
            "Prestige",
            "RS",
            "Standard",
            "Other"
        ]
    },
    {
        "model": "Audi SQ5",
        "trims": [
            "Other",
            "S-Line",
            "TFSI Quattro"
        ]
    },
    {
        "model": "Audi R8",
        "trims": [
            "GT",
            "GT Spyder",
            "Sport",
            "Sport Plus",
            "Sports",
            "Sports Plus",
            "Spyder",
            "Standard",
            "Other"
        ]
    },
    {
        "model": "Audi S4/RS4",
        "trims": [
            "RS",
            "Standard",
            "Other"
        ]
    },
    {
        "model": "Audi S3",
        "trims": [
            "TFSI",
            "TFSI Quattro",
            "Other"
        ]
    },
    {
        "model": "Audi RS e-tron",
        "trims": [
            "GT",
            "Other"
        ]
    },
    {
        "model": "Audi Q8",
        "trims": [
            "3.0 TFSI Quattro",
            "55 TFSI Quattro",
            "55TFSI",
            "E-Tron",
            "Luxury",
            "Premium",
            "RS",
            "RS Q8",
            "S-Line",
            "S-Line Sports",
            "Sport",
            "Other"
        ]
    },
    {
        "model": "Audi RSQ3",
        "trims": [
            "RS",
            "Standard",
            "TFSI Quattro",
            "Other"
        ]
    },
    {
        "model": "Audi Other",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "Audi A3",
        "trims": [
            "1.4 TFSI S tronic",
            "35 TFSI",
            "35 TFSI S-Tronic",
            "35 TFSI Sport",
            "40 TFSI",
            "Ambition",
            "Attraction",
            "S-Line",
            "Standard",
            "Other"
        ]
    },
    {
        "model": "Aurus Senat",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "Austin-Healey Other",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "Austin-Healey 3000",
        "trims": [
            "Mark III BJ8",
            "Other"
        ]
    },
    {
        "model": "Avatr 11",
        "trims": [
            "Premium",
            "Sport",
            "Other"
        ]
    },
    {
        "model": "Avatr 07",
        "trims": [
            "Max EV Edition",
            "Max EV Explore Edition",
            "Max REEV Edition",
            "Max REEV Explore Edition",
            "Other",
            "Pro+ EV Edition",
            "Pro+ REEV Edition",
            "Ultra EV Edition AWD",
            "Ultra REEV Edition AWD"
        ]
    },
    {
        "model": "Avatr Other",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "Avatr 12",
        "trims": [
            "GT",
            "Luxury",
            "Max",
            "Performance",
            "Ultra",
            "Other"
        ]
    },
    {
        "model": "BAC Mono",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "BAIC MZ40",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "BAIC BJ60",
        "trims": [
            "Standard",
            "Other"
        ]
    },
    {
        "model": "BAIC X7",
        "trims": [
            "Honor",
            "Premium",
            "Other"
        ]
    },
    {
        "model": "BAIC A1",
        "trims": [
            "Basic",
            "Comfort",
            "Fashion",
            "Other"
        ]
    },
    {
        "model": "BAIC X55",
        "trims": [
            "Honor",
            "Premium",
            "Other"
        ]
    },
    {
        "model": "BAIC A113",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "BAIC K21",
        "trims": [
            "K21",
            "Other"
        ]
    },
    {
        "model": "BAIC BJ40 SE",
        "trims": [
            "Standard",
            "Other"
        ]
    },
    {
        "model": "BAIC A523",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "BAIC A5",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "BAIC A115",
        "trims": [
            "Basic",
            "Comfort",
            "Fashion",
            "Other"
        ]
    },
    {
        "model": "BAIC D20",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "BAIC BJ40 C",
        "trims": [
            "Standard",
            "Other"
        ]
    },
    {
        "model": "BAIC Other",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "BAIC F40",
        "trims": [
            "Standard",
            "Other"
        ]
    },
    {
        "model": "BAIC BJ40L",
        "trims": [
            "BJ40L",
            "Other"
        ]
    },
    {
        "model": "BAIC BJ80",
        "trims": [
            "Honor",
            "Zomol",
            "Other"
        ]
    },
    {
        "model": "BAIC X424",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "BAIC MZ45",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "BAIC X35",
        "trims": [
            "Elite",
            "Fashion",
            "Fashion Plus",
            "Luxury",
            "Other"
        ]
    },
    {
        "model": "BAW 212 TO1",
        "trims": [
            "Adventurer",
            "Machinist",
            "Officer"
        ]
    },
    {
        "model": "BAW MPV",
        "trims": [
            "M7",
            "Other"
        ]
    },
    {
        "model": "BAW Pick up",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "BAW Small Truck",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "Bentley Azure",
        "trims": [
            "Standard",
            "Other"
        ]
    },
    {
        "model": "Bentley Brooklands",
        "trims": [
            "Standard",
            "Other"
        ]
    },
    {
        "model": "Bentley Continental",
        "trims": [
            "Flying Spur",
            "GTC Supersports",
            "GTC Speed Plus",
            "GTC Speed",
            "GTC S Plus",
            "GTC S",
            "GTC Plus",
            "GTC Mulliner",
            "GTC",
            "GT3-R",
            "GT W12",
            "GT V8 S",
            "GT V8",
            "GT T",
            "GT Supersports",
            "GT Speed Special Edition",
            "GT Speed",
            "GT Special Edition",
            "GT S Special Edition",
            "GT S",
            "GT Mansory 63",
            "GT Concours Series",
            "GT",
            "Flying Spur Speed Plus",
            "Flying Spur Speed",
            "First Edition",
            "Other"
        ]
    },
    {
        "model": "Bentley Other",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "Bentley Mulsanne",
        "trims": [
            "Extended Wheelbase",
            "L",
            "Majestic",
            "Special Edition",
            "Speed",
            "Standard",
            "Other"
        ]
    },
    {
        "model": "Bentley Arnage",
        "trims": [
            "R",
            "RL",
            "T",
            "Other"
        ]
    },
    {
        "model": "Bentley Bentayga",
        "trims": [
            "Design Series",
            "EWB Azure",
            "First Edition",
            "Onyx Edition",
            "Signature",
            "Special Edition",
            "Standard",
            "W12 AWD",
            "W12 First Edition AWD",
            "W12 Mulliner",
            "W12 Speed",
            "Other"
        ]
    },
    {
        "model": "Bentley Flying Spur",
        "trims": [
            "Azure",
            "Hybrid",
            "Mulliner",
            "S",
            "Speed",
            "Standard",
            "V8 S",
            "W12",
            "W12 Speed",
            "Other"
        ]
    },
    {
        "model": "Bentley Onyx Other",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "Bentley Onyx GTX II",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "Bentley Onyx GTX 4x4",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "Bentley Onyx GTX III",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "Bentley Onyx GTX I",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "Bestune B30",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "Bestune B70S",
        "trims": [
            "Limousine",
            "Premium",
            "Other"
        ]
    },
    {
        "model": "Bestune X80",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "Bestune Other",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "Bestune B50",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "Bestune B70",
        "trims": [
            "Comfort",
            "Deluxe",
            "Limousine",
            "Premium",
            "Other"
        ]
    },
    {
        "model": "Bestune T77",
        "trims": [
            "Comfort",
            "Deluxe",
            "Limousine",
            "Luxury",
            "Premium",
            "Other"
        ]
    },
    {
        "model": "Bestune X40",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "Bestune T55",
        "trims": [
            "Comfort",
            "Deluxe",
            "Limousine",
            "Premium",
            "Other"
        ]
    },
    {
        "model": "Bestune T99",
        "trims": [
            "Deluxe",
            "Flago",
            "Limousine",
            "Limousine Sport",
            "Premium",
            "Premium Sport",
            "Sporty",
            "Other"
        ]
    },
    {
        "model": "Bestune T33",
        "trims": [
            "Luxury",
            "Premium",
            "Other"
        ]
    },
    {
        "model": "Bestune B90",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "Bestune T77 Pro",
        "trims": [
            "Concept",
            "Deluxe",
            "Premium",
            "Other"
        ]
    },
    {
        "model": "Bizzarrini Other",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "BMW 4-Series",
        "trims": [
            "440i Convertible",
            "430i xDrive Gran Coupe",
            "435i",
            "435i Convertible",
            "435i Gran Coupe",
            "435i Luxury-line",
            "435i Modern-line",
            "435i Sport-line",
            "440i",
            "420i",
            "440i Gran Coupe",
            "440i xDrive",
            "440i xDrive Convertible",
            "440i xDrive Gran Coupe",
            "M4",
            "M440i xDrive",
            "M440i xDrive Convertible",
            "M440i xDrive Gran Coupe",
            "430i xDrive",
            "418i",
            "420i Convertible",
            "420i Gran Coupe",
            "420i M Sport",
            "420i xDrive",
            "420i xDrive Gran Coupe",
            "428i",
            "428i Convertible",
            "428i Gran Coupe",
            "428i Luxury-line",
            "428i Modern-line",
            "428i Sport-line",
            "430i",
            "430i Convertible",
            "430i Gran Coupe",
            "430i M Sport",
            "430i xDrive Convertible",
            "Other"
        ]
    },
    {
        "model": "BMW M1",
        "trims": [
            "M1",
            "Other"
        ]
    },
    {
        "model": "BMW Other",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "BMW M8",
        "trims": [
            "Gran Coupe Competition",
            "M8 Competition",
            "M8 Convertible",
            "M8 Coupe",
            "M8 Gran Coupe",
            "Other"
        ]
    },
    {
        "model": "BMW iX",
        "trims": [
            "xDrive30",
            "xDrive40",
            "xDrive50",
            "Other"
        ]
    },
    {
        "model": "BMW X6",
        "trims": [
            "Standard",
            "XDrive50i M Sport",
            "Xdrive50i",
            "xDrive40i M Sport",
            "xDrive40i",
            "Xdrive35i Executive",
            "Xdrive35i Exclusive",
            "Xdrive35i",
            "X6M Competition",
            "X6M",
            "4.4i",
            "sDrive35i",
            "M60i",
            "M50i",
            "50i M Sport",
            "4.4T M XDrive Competition",
            "4.4T M XDrive",
            "4.4L M Sport",
            "4.4i V8",
            "Other"
        ]
    },
    {
        "model": "BMW X5",
        "trims": [
            "Xdrive35i Executive",
            "V6",
            "V8",
            "X5M",
            "X5M Competition",
            "Xdrive 40i",
            "xDrive35i",
            "Xdrive35i Dominator",
            "Xdrive35i Exclusive",
            "sDrive40i",
            "xDrive35i Luxury-Line",
            "Xdrive35i M Dominator",
            "xDrive35i M Sport",
            "xDrive40e",
            "xDrive40i M Sport",
            "Xdrive50i",
            "xDrive50i Luxury-Line",
            "xDrive50i M Sport",
            "M",
            "3.0si",
            "40i M-Kit",
            "4.4i",
            "4.4T M",
            "4.4T M XDrive Competition",
            "4.6is",
            "4.8i",
            "4.8is",
            "3.0i",
            "M 35i",
            "M35i",
            "M50i",
            "M60i",
            "sDrive35i",
            "sDrive35i Luxury-Line",
            "sDrive35i M Sport",
            "Other"
        ]
    },
    {
        "model": "BMW X1",
        "trims": [
            "xDrive 20i M Sport",
            "xDrive35i",
            "Xdrive28i",
            "xDrive25i xLine",
            "xDrive25i Sport-Line",
            "xDrive25i M Sport",
            "Xdrive25i",
            "xDrive23d",
            "Xdrive20i",
            "xDrive20d",
            "xDrive18d",
            "I-4",
            "sDrive20i xLine",
            "sDrive20i Sport-Line",
            "sDrive20i M Sport",
            "sDrive20i",
            "sDrive20d",
            "Sdrive18i",
            "sDrive18d",
            "LCI",
            "Other"
        ]
    },
    {
        "model": "BMW M4",
        "trims": [
            "Competition",
            "Competition xDrive M-Kit",
            "Convertible",
            "Coupe",
            "Other"
        ]
    },
    {
        "model": "BMW Z3",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "BMW 8-Series",
        "trims": [
            "840i",
            "840i Gran Coupe",
            "840i M Sport Gran Coupe",
            "850i",
            "850i Gran Coupe",
            "M850i xDrive",
            "M850i xDrive Gran Coupe",
            "Other"
        ]
    },
    {
        "model": "BMW iX3",
        "trims": [
            "MSport",
            "Other"
        ]
    },
    {
        "model": "BMW Z4",
        "trims": [
            "2.5i",
            "2.5si",
            "3.0i",
            "3.0si",
            "M40i",
            "sDrive18i",
            "sDrive20i",
            "Sdrive23i",
            "sDrive28i",
            "Sdrive30i",
            "Sdrive35i",
            "sDrive35is",
            "SDrive40i M Sport",
            "Z4M",
            "Z4M Coupe",
            "Other"
        ]
    },
    {
        "model": "BMW M5",
        "trims": [
            "Standard",
            "M5 Competition",
            "L",
            "T",
            "Other"
        ]
    },
    {
        "model": "BMW M-Coupe",
        "trims": [
            "Z3 Coupe",
            "Other"
        ]
    },
    {
        "model": "BMW 3-Series",
        "trims": [
            "335i Xdrive",
            "330ci",
            "330e",
            "330e xDrive",
            "330i",
            "330i Exclusive",
            "330i Executive",
            "330i Gran Turismo",
            "330i xDrive",
            "335i",
            "335i Gran Turismo",
            "335i Modern-line",
            "316i Exclusive",
            "335is",
            "335xi",
            "340i",
            "340i Gran Turismo",
            "340i xDrive",
            "M 3",
            "M 3 E46",
            "M 3 Limited Edition",
            "M3",
            "M340i",
            "M340i xDrive",
            "328i Sport-line",
            "316i",
            "316i Executive",
            "318ci",
            "318i",
            "318i Exclusive",
            "318i Executive",
            "318ti",
            "320ci",
            "320i",
            "320i Executive",
            "320i Modern-line",
            "320i Standard",
            "320i xDrive",
            "323i",
            "325ci",
            "325i",
            "325i Exclusive",
            "325i Executive",
            "328D",
            "328i",
            "328i GT",
            "328i Luxury-line",
            "328i Standard",
            "Other"
        ]
    },
    {
        "model": "BMW M-Roadster",
        "trims": [
            "Z3 Roadster",
            "Other"
        ]
    },
    {
        "model": "BMW 7-Series",
        "trims": [
            "750li Executive",
            "740Li xDrive",
            "745i",
            "745li",
            "750i",
            "750i Exclusive",
            "750i Executive",
            "750i xDrive",
            "750Li",
            "750li Exclusive",
            "730i Exclusive",
            "750li Luxury",
            "750Li xDrive",
            "760i",
            "760Li",
            "760li Luxury",
            "760Li xDrive",
            "Alpina B7",
            "M 760i xDrive",
            "740li Executive",
            "730i",
            "730i Executive",
            "730Li",
            "730li Exclusive",
            "730li Executive",
            "735i",
            "735li",
            "740E xDrive i Performance",
            "740i",
            "740i Exclusive",
            "740i Executive",
            "740i xDrive",
            "740LE",
            "740LE xDrive",
            "740Li",
            "740li Exclusive",
            "740li Luxury",
            "Other"
        ]
    },
    {
        "model": "BMW X7",
        "trims": [
            "40i M Sport",
            "40i Pure Excellence",
            "4.4 V8",
            "50i M Sport",
            "50i Pure Excellence",
            "M50i M Sport",
            "M60i",
            "Standard",
            "xDrive40i",
            "XDrive50i",
            "xDrive50i Exclusive",
            "XDrive50i M Sport",
            "Other"
        ]
    },
    {
        "model": "BMW M2",
        "trims": [
            "M2",
            "M2 Competition",
            "Other"
        ]
    },
    {
        "model": "BMW Z8",
        "trims": [
            "Other"
        ]
    },
    {
        "model": "BMW i8",
        "trims": [
            "Coupe",
            "Roadster",
            "Standard",
            "Other"
        ]
    },
    {
        "model": "BMW 2-Series",
        "trims": [
            "218i",
            "218i Gran Coupe",
            "220i",
            "220i Convertible",
            "225i",
            "228i",
            "228i Convertible",
            "230i",
            "230i Convertible",
            "240i",
            "M 240i",
            "M2",
            "M235i",
            "Other"
        ]
    },
    {
        "model": "BMW 6-Series",
        "trims": [
            "650i Gran Coupe xDrive Excellence",
            "650ci",
            "650i",
            "650i Excellence",
            "650i Experience",
            "650i Gran Coupe",
            "650i Gran Coupe Excellence",
            "650i Gran Coupe Experience",
            "650i Gran Coupe M Sport",
            "640i",
            "650i Gran Coupe xDrive Experience",
            "650i Gran Coupe xDrive M Sport",
            "650i M Sport",
            "650i xDrive Excellence",
            "650i xDrive Experience",
            "650i xDrive M Sport",
            "M6",
            "M6 Gran Coupe",
            "645ci",
            "630i",
            "640i Excellence"
        ]
    }
]